apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: bond-graalvmee-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: bond-graalvmee-workload
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: "ghcr.io/nelvadas/bondpricing:1.0-native-basic"
        ports:
          - containerPort: 8080
            name: springboot
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: bond-graalvm-appconf
  annotations:
    version: v1.0.0
    description: "Bond Pricing app GraalVM EE Native Image "
spec:
  components:
    - componentName: bond-graalvmee-component
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
              scraper: verrazzano-system/vmi-system-prometheus-0
              path: "/actuator/prometheus"
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: springboot-graalvmee-ingress
            spec:
              rules:
                - paths:
                    - path: "/"
                      pathType: Prefix
---

