micronaut:
  application:
    name: mnBondPricing
  metrics:
    enabled: true
    binders:
      files:
        enabled: true
      jdbc:
        enabled: true
      jvm:
        enabled: true
      logback:
        enabled: true
      processor:
        enabled: true
      uptime:
        enabled: true
      web:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
endpoints:
  prometheus:
    sensitive: false
netty:
  default:
    allocator:
      max-order: 3
